-- Font / text overlay
swayimg.text.set_font("JetBrainsMono NF")
swayimg.text.set_size(10)
swayimg.text.set_foreground(0xffcdd6f4) -- #cdd6f4
swayimg.text.set_shadow(0xd0000000) -- #000000d0
swayimg.text.set_background(0x00000000) -- transparent

-- Viewer mode
swayimg.viewer.set_window_background(0xcc11111b) -- #11111bcc
swayimg.viewer.set_image_background(0xcc11111b) -- #11111bcc (transparency bg)
swayimg.viewer.set_default_scale("optimal")
swayimg.viewer.set_default_position("center")
swayimg.enable_antialiasing(true) -- mks13 is default when antialiasing enabled

-- Viewer info text layout
swayimg.viewer.set_text("topleft", {})
swayimg.viewer.set_text("topright", {})
swayimg.viewer.set_text("bottomleft", { "{name}" })
swayimg.viewer.set_text("bottomright", { "{scale}" })

-- Gallery mode
swayimg.gallery.set_thumb_size(200)
swayimg.gallery.limit_cache(100)
swayimg.gallery.enable_preload(false)
swayimg.gallery.enable_pstore(false)
swayimg.gallery.set_aspect("fill")
swayimg.gallery.set_window_color(0xcc11111b) -- #11111bcc
swayimg.gallery.set_unselected_color(0xcc11111b) -- #11111bcc
swayimg.gallery.set_selected_color(0xcc313244) -- #313244cc
swayimg.gallery.set_border_color(0xffb4befe) -- #b4befeff (lavender)

-- Gallery info text layout
swayimg.gallery.set_text("topleft", {})
swayimg.gallery.set_text("topright", { "{list.index} of {list.total}" })
swayimg.gallery.set_text("bottomleft", {})
swayimg.gallery.set_text("bottomright", { "{name}", "{status}" })

-- Slideshow info text layout
swayimg.slideshow.set_text("topleft", {})
swayimg.slideshow.set_text("topright", {})
swayimg.slideshow.set_text("bottomleft", {})
swayimg.slideshow.set_text("bottomright", { "{dir}", "{status}" })

---------------------------------------------------------------------------
-- Viewer keybindings
---------------------------------------------------------------------------
swayimg.viewer.bind_reset()

swayimg.viewer.on_key("F1", function() end) -- help (built-in, no-op override)
swayimg.viewer.on_key("Home", function()
	swayimg.viewer.switch_image("first")
end)
swayimg.viewer.on_key("End", function()
	swayimg.viewer.switch_image("last")
end)

-- vim movement: drag image
swayimg.viewer.on_key("h", function()
	swayimg.viewer.set_fix_position(swayimg.viewer.get_position().x + 10, swayimg.viewer.get_position().y)
end)
swayimg.viewer.on_key("j", function()
	swayimg.viewer.set_fix_position(swayimg.viewer.get_position().x, swayimg.viewer.get_position().y - 10)
end)
swayimg.viewer.on_key("k", function()
	swayimg.viewer.set_fix_position(swayimg.viewer.get_position().x, swayimg.viewer.get_position().y + 10)
end)
swayimg.viewer.on_key("l", function()
	swayimg.viewer.set_fix_position(swayimg.viewer.get_position().x - 10, swayimg.viewer.get_position().y)
end)

swayimg.viewer.on_key("Shift-h", function()
	swayimg.viewer.switch_image("prev")
end)
swayimg.viewer.on_key("Shift-l", function()
	swayimg.viewer.switch_image("next")
end)
swayimg.viewer.on_key("Space", function()
	swayimg.viewer.switch_image("next")
end)
swayimg.viewer.on_key("Shift-r", function()
	swayimg.viewer.switch_image("rand")
end)
swayimg.viewer.on_key("Shift-d", function()
	swayimg.viewer.switch_image("prevdir")
end)
swayimg.viewer.on_key("d", function()
	swayimg.viewer.switch_image("nextdir")
end)
swayimg.viewer.on_key("Shift-o", function()
	swayimg.viewer.prev_frame()
end)
swayimg.viewer.on_key("o", function()
	swayimg.viewer.set_fix_scale(swayimg.viewer.get_scale() - swayimg.viewer.get_scale() / 10)
end)
swayimg.viewer.on_key("i", function()
	swayimg.viewer.set_fix_scale(swayimg.viewer.get_scale() + swayimg.viewer.get_scale() / 10)
end)
swayimg.viewer.on_key("c", function()
	swayimg.viewer.switch_image("skip")
end)
swayimg.viewer.on_key("s", function()
	swayimg.set_mode("slideshow")
end)
swayimg.viewer.on_key("n", function()
	swayimg.viewer.set_animation(not swayimg.viewer.get_animation())
end)
swayimg.viewer.on_key("f", function()
	swayimg.toggle_fullscreen()
end)
swayimg.viewer.on_key("Return", function()
	swayimg.set_mode("gallery")
end)

swayimg.viewer.on_key("Left", function()
	local p = swayimg.viewer.get_position()
	swayimg.viewer.set_fix_position(p.x + 10, p.y)
end)
swayimg.viewer.on_key("Right", function()
	local p = swayimg.viewer.get_position()
	swayimg.viewer.set_fix_position(p.x - 10, p.y)
end)
swayimg.viewer.on_key("Up", function()
	local p = swayimg.viewer.get_position()
	swayimg.viewer.set_fix_position(p.x, p.y + 10)
end)
swayimg.viewer.on_key("Down", function()
	local p = swayimg.viewer.get_position()
	swayimg.viewer.set_fix_position(p.x, p.y - 10)
end)

swayimg.viewer.on_key("Equal", function()
	swayimg.viewer.set_fix_scale(swayimg.viewer.get_scale() + swayimg.viewer.get_scale() / 10)
end)
swayimg.viewer.on_key("Plus", function()
	swayimg.viewer.set_fix_scale(swayimg.viewer.get_scale() + swayimg.viewer.get_scale() / 10)
end)
swayimg.viewer.on_key("Minus", function()
	swayimg.viewer.set_fix_scale(swayimg.viewer.get_scale() - swayimg.viewer.get_scale() / 10)
end)
swayimg.viewer.on_key("w", function()
	swayimg.viewer.set_fix_scale("width")
end)
swayimg.viewer.on_key("Shift-w", function()
	swayimg.viewer.set_fix_scale("height")
end)
swayimg.viewer.on_key("z", function()
	swayimg.viewer.set_fix_scale("fit")
end)
swayimg.viewer.on_key("Shift-z", function()
	swayimg.viewer.set_fix_scale("fill")
end)
swayimg.viewer.on_key("0", function()
	swayimg.viewer.set_fix_scale("optimal")
end)
swayimg.viewer.on_key("BackSpace", function()
	swayimg.viewer.set_fix_scale("optimal")
end)

swayimg.viewer.on_key("bracketleft", function()
	swayimg.viewer.rotate(-90)
end)
swayimg.viewer.on_key("bracketright", function()
	swayimg.viewer.rotate(90)
end)
swayimg.viewer.on_key("m", function()
	swayimg.viewer.flip_vertical()
end)
swayimg.viewer.on_key("Shift-m", function()
	swayimg.viewer.flip_horizontal()
end)
swayimg.viewer.on_key("a", function()
	swayimg.enable_antialiasing(not swayimg.viewer.get_scale())
end)
swayimg.viewer.on_key("r", function()
	swayimg.viewer.reload()
end)

swayimg.viewer.on_key("Shift-Delete", function()
	local img = swayimg.viewer.get_image()
	os.remove(img.path)
	swayimg.text.set_status("File removed: " .. img.path)
	swayimg.viewer.switch_image("skip")
end)

swayimg.viewer.on_key("Escape", function()
	swayimg.exit()
end)
swayimg.viewer.on_key("q", function()
	swayimg.exit()
end)

swayimg.viewer.on_mouse("ScrollLeft", function()
	swayimg.viewer.set_fix_position(swayimg.viewer.get_position().x - 5, swayimg.viewer.get_position().y)
end)
swayimg.viewer.on_mouse("ScrollRight", function()
	swayimg.viewer.set_fix_position(swayimg.viewer.get_position().x + 5, swayimg.viewer.get_position().y)
end)
swayimg.viewer.on_mouse("ScrollUp", function()
	swayimg.viewer.set_fix_position(swayimg.viewer.get_position().x, swayimg.viewer.get_position().y + 5)
end)
swayimg.viewer.on_mouse("ScrollDown", function()
	swayimg.viewer.set_fix_position(swayimg.viewer.get_position().x, swayimg.viewer.get_position().y - 5)
end)
swayimg.viewer.on_mouse("Ctrl-ScrollUp", function()
	local pos = swayimg.get_mouse_pos()
	swayimg.viewer.set_abs_scale(swayimg.viewer.get_scale() + swayimg.viewer.get_scale() / 10, pos.x, pos.y)
end)
swayimg.viewer.on_mouse("Ctrl-ScrollDown", function()
	local pos = swayimg.get_mouse_pos()
	swayimg.viewer.set_abs_scale(swayimg.viewer.get_scale() - swayimg.viewer.get_scale() / 10, pos.x, pos.y)
end)
swayimg.viewer.on_mouse("Shift-ScrollUp", function()
	swayimg.viewer.switch_image("prev")
end)
swayimg.viewer.on_mouse("Shift-ScrollDown", function()
	swayimg.viewer.switch_image("next")
end)
swayimg.viewer.on_mouse("Alt-ScrollUp", function()
	swayimg.viewer.prev_frame()
end)
swayimg.viewer.on_mouse("Alt-ScrollDown", function()
	swayimg.viewer.next_frame()
end)
swayimg.viewer.on_mouse("MouseLeft", function()
	swayimg.viewer.set_drag_button("MouseLeft")
end)
swayimg.viewer.on_mouse("MouseSide", function()
	swayimg.viewer.switch_image("prev")
end)
swayimg.viewer.on_mouse("MouseExtra", function()
	swayimg.viewer.switch_image("next")
end)

---------------------------------------------------------------------------
-- Slideshow keybindings
---------------------------------------------------------------------------
swayimg.slideshow.bind_reset()

swayimg.slideshow.on_key("F1", function() end)
swayimg.slideshow.on_key("Home", function()
	swayimg.slideshow.switch_image("first")
end)
swayimg.slideshow.on_key("End", function()
	swayimg.slideshow.switch_image("last")
end)
swayimg.slideshow.on_key("h", function()
	local p = swayimg.slideshow.get_position()
	swayimg.slideshow.set_fix_position(p.x + 10, p.y)
end)
swayimg.slideshow.on_key("j", function()
	local p = swayimg.slideshow.get_position()
	swayimg.slideshow.set_fix_position(p.x, p.y - 10)
end)
swayimg.slideshow.on_key("k", function()
	local p = swayimg.slideshow.get_position()
	swayimg.slideshow.set_fix_position(p.x, p.y + 10)
end)
swayimg.slideshow.on_key("l", function()
	local p = swayimg.slideshow.get_position()
	swayimg.slideshow.set_fix_position(p.x - 10, p.y)
end)
swayimg.slideshow.on_key("Shift-r", function()
	swayimg.slideshow.switch_image("rand")
end)
swayimg.slideshow.on_key("Shift-d", function()
	swayimg.slideshow.switch_image("prevdir")
end)
swayimg.slideshow.on_key("d", function()
	swayimg.slideshow.switch_image("nextdir")
end)
swayimg.slideshow.on_key("Space", function()
	swayimg.slideshow.set_animation(not swayimg.slideshow.get_animation())
end)
swayimg.slideshow.on_key("i", function()
	swayimg.slideshow.set_fix_scale(swayimg.slideshow.get_scale() + swayimg.slideshow.get_scale() / 10)
end)
swayimg.slideshow.on_key("o", function()
	swayimg.slideshow.set_fix_scale(swayimg.slideshow.get_scale() - swayimg.slideshow.get_scale() / 10)
end)
swayimg.slideshow.on_key("f", function()
	swayimg.toggle_fullscreen()
end)
swayimg.slideshow.on_key("Return", function()
	swayimg.set_mode("viewer")
end)
swayimg.slideshow.on_key("Escape", function()
	swayimg.exit()
end)
swayimg.slideshow.on_key("q", function()
	swayimg.exit()
end)

---------------------------------------------------------------------------
-- Gallery keybindings
---------------------------------------------------------------------------
swayimg.gallery.bind_reset()

swayimg.gallery.on_key("F1", function() end)
swayimg.gallery.on_key("Home", function()
	swayimg.gallery.switch_image("first")
end)
swayimg.gallery.on_key("End", function()
	swayimg.gallery.switch_image("last")
end)
swayimg.gallery.on_key("h", function()
	swayimg.gallery.switch_image("left")
end)
swayimg.gallery.on_key("j", function()
	swayimg.gallery.switch_image("down")
end)
swayimg.gallery.on_key("k", function()
	swayimg.gallery.switch_image("up")
end)
swayimg.gallery.on_key("l", function()
	swayimg.gallery.switch_image("right")
end)
swayimg.gallery.on_key("Left", function()
	swayimg.gallery.switch_image("left")
end)
swayimg.gallery.on_key("Right", function()
	swayimg.gallery.switch_image("right")
end)
swayimg.gallery.on_key("Up", function()
	swayimg.gallery.switch_image("up")
end)
swayimg.gallery.on_key("Down", function()
	swayimg.gallery.switch_image("down")
end)
swayimg.gallery.on_key("c", function()
	swayimg.gallery.switch_image("skip")
end)
swayimg.gallery.on_key("s", function()
	swayimg.set_mode("slideshow")
end)
swayimg.gallery.on_key("f", function()
	swayimg.toggle_fullscreen()
end)
swayimg.gallery.on_key("Return", function()
	swayimg.set_mode("viewer")
end)
swayimg.gallery.on_key("a", function()
	swayimg.enable_antialiasing(true)
end)
swayimg.gallery.on_key("r", function()
	swayimg.gallery.reload()
end)
swayimg.gallery.on_key("i", function()
	swayimg.set_mode("viewer")
end)
swayimg.gallery.on_key("o", function()
	swayimg.set_mode("viewer")
end)
swayimg.gallery.on_key("Equal", function()
	swayimg.gallery.set_thumb_size(swayimg.gallery.get_thumb_size() + 20)
end)
swayimg.gallery.on_key("Plus", function()
	swayimg.gallery.set_thumb_size(swayimg.gallery.get_thumb_size() + 20)
end)
swayimg.gallery.on_key("Minus", function()
	swayimg.gallery.set_thumb_size(swayimg.gallery.get_thumb_size() - 20)
end)

swayimg.gallery.on_key("Shift-Delete", function()
	local img = swayimg.gallery.get_image()
	os.remove(img.path)
	swayimg.text.set_status("File removed: " .. img.path)
	swayimg.gallery.switch_image("skip")
end)

swayimg.gallery.on_key("Escape", function()
	swayimg.exit()
end)
swayimg.gallery.on_key("q", function()
	swayimg.exit()
end)

swayimg.gallery.on_mouse("ScrollLeft", function()
	swayimg.gallery.switch_image("right")
end)
swayimg.gallery.on_mouse("ScrollRight", function()
	swayimg.gallery.switch_image("left")
end)
swayimg.gallery.on_mouse("ScrollUp", function()
	swayimg.gallery.switch_image("up")
end)
swayimg.gallery.on_mouse("ScrollDown", function()
	swayimg.gallery.switch_image("down")
end)
swayimg.gallery.on_mouse("Ctrl-ScrollUp", function()
	swayimg.gallery.set_thumb_size(swayimg.gallery.get_thumb_size() + 20)
end)
swayimg.gallery.on_mouse("Ctrl-ScrollDown", function()
	swayimg.gallery.set_thumb_size(swayimg.gallery.get_thumb_size() - 20)
end)
swayimg.gallery.on_mouse("MouseLeft", function()
	swayimg.set_mode("viewer")
end)
