{ config, pkgs, ... }:
let
  gtkCss = ''
    /* generated by setup script */

    @import url("noctalia.css");

    window {
        background: alpha(@window_bg_color, ${toString config.stylix.opacity.applications});
    }

    .sidebar-pane,
    .sidebar,
    .navigation-sidebar {
        background: transparent;
    }
  '';
in
{
  home.packages = with pkgs; [
    (writeShellScriptBin "setup-noctalia" ''
      cat ~/.config/noctalia/config.toml > ~/.local/state/noctalia/settings.toml

      noctalia msg templates-apply

      printf '%s\n' '${gtkCss}' > "$HOME/.config/gtk-4.0/gtk.css"
    '')
  ];
}
